spring.application.name=Antss_Prescription

spring.datasource.url=jdbc:postgresql://localhost:5432/antss_prescription
#spring.datasource.username=postgres
#spring.datasource.password=root
spring.datasource.username=shreeauraroot
spring.datasource.password=rootshreeaura
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=RishBootDevAntssPrescription2374646383937836723748474
app.jwt.access-token-expiration=3600000
app.jwt.refresh-token-expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=antss9755@gmail.com
spring.mail.password=hglc qcdm umli yoza

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.admin.email=antss9755@gmail.com
app.admin.default-password=Admin@123

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


cloudinary.key=249827298598285
cloudinary.secret=UmfXD0HvMAKNOtuynqQl6GpUR0Q
cloudinary.cloud-name=dzr8leuza

server.port=2030
app.base-url=https://api.antss.in
app.owner-frontend-url=http://www.antss.in
app.prescription-frontend-url=https://prescription.antss.in
app.pdf.unicode-font-path=/usr/share/fonts/truetype/noto/NotoSansDevanagari-Regular.ttf
