package com.antss_prescription.controller;

import com.antss_prescription.dto.request.CreatePrescriptionRequest;
import com.antss_prescription.dto.response.ApiResponse;
import com.antss_prescription.dto.response.PrescriptionResponse;
import com.antss_prescription.entity.User;
import com.antss_prescription.exception.ResourceNotFoundException;
import com.antss_prescription.repository.UserRepository;
import com.antss_prescription.service.PrescriptionService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/prescriptions")
@SecurityRequirement(name = "bearerAuth")
@Tag(name = "Prescription APIs", description = "Patient prescription management and print-ready metadata")
public class PrescriptionController {

    private final PrescriptionService prescriptionService;
    private final UserRepository userRepository;

    public PrescriptionController(PrescriptionService prescriptionService, UserRepository userRepository) {
        this.prescriptionService = prescriptionService;
        this.userRepository = userRepository;
    }

    @PostMapping
    @Operation(summary = "Create a new patient prescription")
    public ResponseEntity<ApiResponse<PrescriptionResponse>> createPrescription(@Valid @RequestBody CreatePrescriptionRequest request) {
        UUID userId = getCurrentUserId();
        PrescriptionResponse response = prescriptionService.createPrescription(request, userId);
        return ResponseEntity.ok(ApiResponse.success("Prescription created successfully", response));
    }

    @GetMapping
    @Operation(summary = "List all prescriptions generated by doctors in this Hospital/Clinic")
    public ResponseEntity<ApiResponse<List<PrescriptionResponse>>> listPrescriptions() {
        UUID userId = getCurrentUserId();
        List<PrescriptionResponse> responses = prescriptionService.getPrescriptions(userId);
        return ResponseEntity.ok(ApiResponse.success("Prescriptions fetched successfully", responses));
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get detailed prescription metadata by ID")
    public ResponseEntity<ApiResponse<PrescriptionResponse>> getPrescriptionById(@PathVariable Long id) {
        UUID userId = getCurrentUserId();
        PrescriptionResponse response = prescriptionService.getPrescriptionById(id, userId);
        return ResponseEntity.ok(ApiResponse.success("Prescription fetched successfully", response));
    }

    private UUID getCurrentUserId() {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("User", email));
        return user.getId();
    }
}
